package TestPackage;

import java.sql.Driver;
import java.util.Iterator;
import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.By.ByCssSelector;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class PopUps {

	//Test will click a button which display a PopUp , this test will allow the program to switch windows between the Main window and the PopUp generated by clicking the button 
	
	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.chrome.driver" , "C:\\Users\\Conor\\OneDrive\\Documents\\FD\\Portfolio\\Web Automation\\drivers\\chromedriver.exe");
		
		WebDriver driver = new ChromeDriver();
		
		driver.manage().window().maximize();
		
		driver.get("https://www.automationtesting.co.uk/popups.html");

		driver.findElement(By.cssSelector("[onclick='popup\\(\\)']")).click();
		
		//Get WindowHandle ID of the Window it has focus of
		String mainWindow = driver.getWindowHandle();
		
		//Set holds the handle IDs - A Set is a Collection that cannot contain duplicate elements
		Set<String> handles = driver.getWindowHandles(); 
		
		// Used to loop through a collection
		Iterator<String> iterate = handles.iterator();
		
		
		//While Loop - if True it will run code in brackets , 
		while(iterate.hasNext()) {
			
			//Store Value of the next Window Handle
			String child = iterate.next();
			
			if(!mainWindow.equalsIgnoreCase(child))
			{
				Thread.sleep(3000);
				driver.switchTo().window(child);
				driver.close();
			}
			
		}
		Thread.sleep(3000);
		driver.switchTo().window(mainWindow);
	}

}
